-- MySQL Script generated by MySQL Workbench
-- Sun Dec 27 17:55:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SuperDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SuperDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SuperDB` DEFAULT CHARACTER SET utf8 ;
USE `SuperDB` ;

-- -----------------------------------------------------
-- Table `SuperDB`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperDB`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `sex` VARCHAR(20) NULL,
  `dateOfBirth` DATETIME NULL,
  `hobbies` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperDB`.`Auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperDB`.`Auth` (
  `idUser` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `auth_user_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `auth_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `SuperDB`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperDB`.`Chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperDB`.`Chats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperDB`.`ChatMembers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperDB`.`ChatMembers` (
  `idChat` INT NOT NULL,
  `idUser` INT NOT NULL,
  INDEX `chatmember_user_idx` (`idUser` ASC) VISIBLE,
  INDEX `chatmember_chat_idx` (`idChat` ASC) VISIBLE,
  CONSTRAINT `chatmember_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `SuperDB`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `chatmember_chat`
    FOREIGN KEY (`idChat`)
    REFERENCES `SuperDB`.`Chats` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuperDB`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuperDB`.`Messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idChat` INT NOT NULL,
  `idUser` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `text` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `messages_users_idx` (`idUser` ASC) VISIBLE,
  INDEX `messages_chats_idx` (`idChat` ASC) VISIBLE,
  CONSTRAINT `messages_users`
    FOREIGN KEY (`idUser`)
    REFERENCES `SuperDB`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `messages_chats`
    FOREIGN KEY (`idChat`)
    REFERENCES `SuperDB`.`Chats` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
